version: '3'
    
services:
  nishika_image_search-container:
    restart: always
    image: nishika_image_search:latest
    container_name: nishika_image_search-container
    build: .
    shm_size: '2gb'
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    stdin_open: true
    tty: true
    ports:
      # ssh
      - "20021:22"
      # tensorboard
      - "6006:6006"
      # jupyterlab
      - "18888:8888"
    # environment:
    #   - TZ: Asia/Tokyo
    volumes:
      - /home/makkimaki/work:/work
      - /home/makkimaki/dataset:/dataset
    command: bash /startup.sh

